apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-apps
spec:
  rules:
  - name: set-defaults
    match:
      all:
      - resources:
          kinds:
          - Application
          operations:
          - CREATE
    exclude:
      any:
      - resources:
          names:
          - "cluster-*"
    context:
    - name: sharedclusters
      configMap:
        name: shared-clusters
        namespace: kyverno
    mutate:
      patchStrategicMerge:
        metadata:
          finalizers:
          - resources-finalizer.argocd.argoproj.io
        spec:
          +(project): default
          destination:
            +(server): "{{ sharedclusters.data.address }}"
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            managedNamespaceMetadata:
              labels:
                argocd.argoproj.io/instance: "{{request.name}}"
                owner: "{{request.object.metadata.labels.owner}}"
              annotations:
                argocd.argoproj.io/tracking-id: >-
                  {{request.name}}:/Namespace:{{request.object.spec.destination.namespace}}/{{request.object.spec.destination.namespace}}
            syncOptions:
            - CreateNamespace=true
